import { Flashcard } from '../types';

// Helper to create cards efficiently
const createCards = (category: string, words: Record<string, string>): Flashcard[] => {
  return Object.entries(words).map(([en, pl], index) => ({
    id: `${category.toLowerCase()}-${index}`,
    en,
    pl,
    category,
    status: 'new'
  }));
};

export const INITIAL_FLASHCARDS: Flashcard[] = [
  ...createCards('Człowiek', {
    'age': 'wiek',
    'angry': 'zły',
    'annoyed': 'zirytowany',
    'appearance': 'wygląd',
    'attractive': 'atrakcyjny',
    'aunt': 'ciocia',
    'baby': 'niemowlę',
    'bald': 'łysy',
    'beard': 'broda',
    'beautiful': 'piękny',
    'birth': 'narodziny',
    'blonde': 'blondyn/ka',
    'bored': 'znudzony',
    'boring': 'nudny',
    'boy': 'chłopiec',
    'brave': 'odważny',
    'brother': 'brat',
    'character': 'charakter',
    'cheerful': 'radosny',
    'child': 'dziecko',
    'clever': 'sprytny/mądry',
    'clothes': 'ubrania',
    'cousin': 'kuzyn/ka',
    'curly': 'kręcone (włosy)',
    'dad': 'tata',
    'daughter': 'córka',
    'divorced': 'rozwiedziony',
    'elderly': 'w podeszłym wieku',
    'excited': 'podekscytowany',
    'eyes': 'oczy',
    'face': 'twarz',
    'fair': 'jasny (włosy)',
    'family': 'rodzina',
    'famous': 'sławny',
    'fat': 'gruby',
    'feelings': 'uczucia',
    'friendly': 'przyjazny',
    'funny': 'zabawny',
    'generation': 'pokolenie',
    'girl': 'dziewczyna',
    'glasses': 'okulary',
    'grandfather': 'dziadek',
    'grandmother': 'babcia',
    'hair': 'włosy',
    'handsome': 'przystojny',
    'happy': 'szczęśliwy',
    'hard-working': 'pracowity',
    'height': 'wzrost',
    'helpful': 'pomocny',
    'honest': 'uczciwy',
    'husband': 'mąż',
    'intelligent': 'inteligentny',
    'jealous': 'zazdrosny',
    'kind': 'miły/uprzejmy',
    'lazy': 'leniwy',
    'look like': 'wyglądać jak',
    'man': 'mężczyzna',
    'married': 'żonaty/zamężna',
    'mean': 'złośliwy/skąpy',
    'middle-aged': 'w średnim wieku',
    'modest': 'skromny',
    'mother': 'matka',
    'moustache': 'wąsy',
    'mum': 'mama',
    'name': 'imię',
    'nationality': 'narodowość',
    'nephew': 'siostrzeniec/bratanek',
    'nice': 'miły',
    'niece': 'siostrzenica/bratanica',
    'nose': 'nos',
    'old': 'stary',
    'overweight': 'z nadwagą',
    'pale': 'blady',
    'parents': 'rodzice',
    'patient': 'cierpliwy',
    'people': 'ludzie',
    'person': 'osoba',
    'personality': 'osobowość',
    'polite': 'uprzejmy',
    'pretty': 'ładna',
    'quiet': 'cichy/spokojny',
    'relationship': 'związek',
    'relative': 'krewny',
    'reliable': 'niezawodny',
    'rude': 'niegrzeczny',
    'sad': 'smutny',
    'scared': 'przestraszony',
    'serious': 'poważny',
    'short': 'niski',
    'shy': 'nieśmiały',
    'single': 'wolny (stan cywilny)',
    'sister': 'siostra',
    'slim': 'szczupły',
    'smart': 'bystry/elegancki',
    'smile': 'uśmiech',
    'son': 'syn',
    'straight': 'proste (włosy)',
    'strong': 'silny',
    'stupid': 'głupi',
    'surname': 'nazwisko',
    'surprised': 'zaskoczony',
    'tall': 'wysoki',
    'teenager': 'nastolatek',
    'thin': 'chudy',
    'tired': 'zmęczony',
    'toddler': 'małe dziecko',
    'ugly': 'brzydki',
    'uncle': 'wujek',
    'wavy': 'falowane (włosy)',
    'weak': 'słaby',
    'wedding': 'ślub',
    'wife': 'żona',
    'woman': 'kobieta',
    'worried': 'zmartwiony',
    'young': 'młody'
  }),
  ...createCards('Dom', {
    'address': 'adres',
    'apartment': 'mieszkanie',
    'armchair': 'fotel',
    'attic': 'strych/poddasze',
    'balcony': 'balkon',
    'basement': 'piwnica',
    'bath': 'wanna',
    'bathroom': 'łazienka',
    'bed': 'łóżko',
    'bedroom': 'sypialnia',
    'block of flats': 'blok mieszkalny',
    'bookcase': 'biblioteczka',
    'carpet': 'dywan',
    'ceiling': 'sufit',
    'chair': 'krzesło',
    'chimney': 'komin',
    'city centre': 'centrum miasta',
    'clean': 'sprzątać/czysty',
    'clock': 'zegar',
    'cooker': 'kuchenka',
    'cottage': 'domek wiejski',
    'countryside': 'wieś',
    'cupboard': 'szafka kuchenna',
    'curtains': 'zasłony',
    'desk': 'biurko',
    'detached house': 'dom jednorodzinny',
    'dining room': 'jadalnia',
    'door': 'drzwi',
    'downstairs': 'na dole (piętro)',
    'drawer': 'szuflada',
    'fireplace': 'kominek',
    'flat': 'mieszkanie',
    'floor': 'podłoga/piętro',
    'fridge': 'lodówka',
    'furniture': 'meble',
    'garage': 'garaż',
    'garden': 'ogród',
    'gate': 'brama',
    'ground floor': 'parter',
    'hall': 'przedpokój',
    'heating': 'ogrzewanie',
    'home': 'dom (ognisko domowe)',
    'house': 'dom (budynek)',
    'housework': 'prace domowe',
    'key': 'klucz',
    'kitchen': 'kuchnia',
    'lamp': 'lampa',
    'lift': 'winda',
    'live': 'mieszkać',
    'living room': 'salon',
    'location': 'lokalizacja',
    'lock': 'zamek',
    'mirror': 'lustro',
    'move in': 'wprowadzić się',
    'move out': 'wyprowadzić się',
    'neighbour': 'sąsiad',
    'neighbourhood': 'sąsiedztwo',
    'oven': 'piekarnik',
    'painting': 'obraz',
    'pillow': 'poduszka',
    'plant': 'roślina',
    'poster': 'plakat',
    'rent': 'wynajmować/czynsz',
    'roof': 'dach',
    'room': 'pokój',
    'rug': 'dywanik',
    'semidetached house': 'bliźniak',
    'share a room': 'dzielić pokój',
    'shelf': 'półka',
    'shower': 'prysznic',
    'sink': 'zlew',
    'sofa': 'kanapa',
    'stairs': 'schody',
    'study': 'gabinet',
    'table': 'stół',
    'terraced house': 'szeregowiec',
    'tidy': 'sprzątać',
    'toilet': 'toaleta',
    'town': 'miasteczko',
    'upstairs': 'na górze (piętro)',
    'village': 'wioska',
    'wall': 'ściana',
    'wardrobe': 'szafa',
    'washing machine': 'pralka',
    'window': 'okno'
  }),
  ...createCards('Szkoła', {
    'absent': 'nieobecny',
    'answer': 'odpowiedź',
    'art': 'plastyka',
    'ask': 'pytać',
    'biology': 'biologia',
    'blackboard': 'tablica',
    'book': 'książka',
    'break': 'przerwa',
    'chemistry': 'chemia',
    'class': 'klasa/lekcja',
    'classmate': 'kolega z klasy',
    'classroom': 'sala lekcyjna',
    'college': 'uczelnia/studium',
    'computer science': 'informatyka',
    'copy': 'kopiować/ściągać',
    'course': 'kurs',
    'desk': 'ławka szkolna',
    'dictionary': 'słownik',
    'do homework': 'odrabiać lekcje',
    'education': 'edukacja',
    'english': 'język angielski',
    'exam': 'egzamin',
    'example': 'przykład',
    'fail': 'oblać (egzamin)',
    'geography': 'geografia',
    'grade': 'ocena/klasa',
    'graduate': 'absolwent/ukończyć szkołę',
    'gym': 'sala gimnastyczna',
    'headmaster': 'dyrektor',
    'history': 'historia',
    'holidays': 'wakacje',
    'homework': 'zadanie domowe',
    'learn': 'uczyć się',
    'lesson': 'lekcja',
    'library': 'biblioteka',
    'map': 'mapa',
    'mark': 'ocena',
    'maths': 'matematyka',
    'mistake': 'błąd',
    'music': 'muzyka',
    'notebook': 'zeszyt',
    'notes': 'notatki',
    'pass': 'zdać (egzamin)',
    'pe': 'wf (wychowanie fizyczne)',
    'pen': 'długopis',
    'pencil': 'ołówek',
    'pencil case': 'piórnik',
    'physics': 'fizyka',
    'playground': 'boisko/plac zabaw',
    'present': 'obecny',
    'primary school': 'szkoła podstawowa',
    'project': 'projekt',
    'pupil': 'uczeń (młodszy)',
    'question': 'pytanie',
    'read': 'czytać',
    'religion': 'religia',
    'revise': 'powtarzać (materiał)',
    'rubber': 'gumka',
    'ruler': 'linijka',
    'school': 'szkoła',
    'school bag': 'plecak',
    'school uniform': 'mundurek',
    'science': 'przedmioty ścisłe',
    'secondary school': 'szkoła średnia',
    'student': 'uczeń/student',
    'study': 'studiować/uczyć się',
    'subject': 'przedmiot szkolny',
    'teacher': 'nauczyciel',
    'term': 'semestr',
    'test': 'test/sprawdzian',
    'textbook': 'podręcznik',
    'timetable': 'plan lekcji',
    'university': 'uniwersytet',
    'whiteboard': 'tablica (biała)',
    'write': 'pisać'
  }),
  ...createCards('Praca', {
    'actor': 'aktor',
    'apply for': 'ubiegać się o',
    'architect': 'architekt',
    'artist': 'artysta',
    'baker': 'piekarz',
    'boss': 'szef',
    'builder': 'budowlaniec',
    'bus driver': 'kierowca autobusu',
    'businessman': 'biznesmen',
    'busy': 'zajęty',
    'career': 'kariera',
    'chef': 'szef kuchni',
    'cleaner': 'sprzątaczka',
    'colleague': 'współpracownik',
    'company': 'firma',
    'cook': 'kucharz',
    'cv': 'życiorys',
    'dentist': 'dentysta',
    'doctor': 'lekarz',
    'driver': 'kierowca',
    'earn': 'zarabiać',
    'electrician': 'elektryk',
    'employee': 'pracownik',
    'employer': 'pracodawca',
    'engineer': 'inżynier',
    'experience': 'doświadczenie',
    'factory': 'fabryka',
    'farm': 'farma',
    'farmer': 'rolnik',
    'firefighter': 'strażak',
    'flight attendant': 'stewardesa',
    'full-time': 'pełny etat',
    'hairdresser': 'fryzjer',
    'holiday job': 'praca wakacyjna',
    'interview': 'rozmowa kwalifikacyjna',
    'job': 'praca (konkretne zajęcie)',
    'journalist': 'dziennikarz',
    'lawyer': 'prawnik',
    'manager': 'kierownik',
    'mechanic': 'mechanik',
    'money': 'pieniądze',
    'musician': 'muzyk',
    'nurse': 'pielęgniarka',
    'office': 'biuro',
    'painter': 'malarz',
    'part-time': 'pół etatu',
    'pay': 'płaca/płacić',
    'pilot': 'pilot',
    'plumber': 'hydraulik',
    'police officer': 'policjant',
    'postman': 'listonosz',
    'profession': 'zawód',
    'programmer': 'programista',
    'promotion': 'awans',
    'quit': 'rzucić (pracę)',
    'receptionist': 'recepcjonista',
    'salary': 'pensja',
    'sales assistant': 'sprzedawca',
    'secretary': 'sekretarka',
    'shop assistant': 'sprzedawca w sklepie',
    'singer': 'piosenkarz',
    'soldier': 'żołnierz',
    'staff': 'personel',
    'taxi driver': 'taksówkarz',
    'teacher': 'nauczyciel',
    'team': 'zespół',
    'unemployed': 'bezrobotny',
    'vet': 'weterynarz',
    'waiter': 'kelner',
    'waitress': 'kelnerka',
    'work': 'praca (ogólnie)',
    'worker': 'robotnik',
    'working hours': 'godziny pracy',
    'writer': 'pisarz'
  }),
  ...createCards('Życie codzienne', {
    'activity': 'zajęcie/aktywność',
    'afternoon': 'popołudnie',
    'appointment': 'wizyta/spotkanie',
    'argue': 'kłócić się',
    'arrive': 'przyjeżdżać',
    'ask for': 'prosić o',
    'bake': 'piec',
    'bank': 'bank',
    'buy': 'kupować',
    'call': 'dzwonić',
    'cash': 'gotówka',
    'celebrate': 'świętować',
    'change': 'reszta (pieniądze)/zmieniać',
    'chat': 'rozmawiać/czatować',
    'cheap': 'tani',
    'check': 'sprawdzać',
    'cinema': 'kino',
    'clean': 'sprzątać',
    'clock': 'zegar',
    'clothes': 'ubrania',
    'collect': 'kolekcjonować/odbierać',
    'comb': 'czesać',
    'come back': 'wracać',
    'computer': 'komputer',
    'concert': 'koncert',
    'cook': 'gotować',
    'cost': 'kosztować',
    'credit card': 'karta kredytowa',
    'customer': 'klient',
    'daily routine': 'codzienne czynności',
    'dance': 'tańczyć',
    'date': 'randka/data',
    'department store': 'dom towarowy',
    'diary': 'pamiętnik',
    'dinner': 'obiad/kolacja',
    'do shopping': 'robić zakupy',
    'drink': 'pić/napój',
    'drive': 'prowadzić (auto)',
    'early': 'wcześnie',
    'eat': 'jeść',
    'email': 'e-mail',
    'evening': 'wieczór',
    'every day': 'codziennie',
    'expensive': 'drogi',
    'free time': 'czas wolny',
    'friend': 'przyjaciel',
    'get dressed': 'ubierać się',
    'get up': 'wstawać',
    'go out': 'wychodzić (z domu)',
    'go to bed': 'iść spać',
    'gym': 'siłownia',
    'habit': 'nawyk',
    'haircut': 'fryzura/strzyżenie',
    'have breakfast': 'jeść śniadanie',
    'help': 'pomagać',
    'hobby': 'hobby',
    'home': 'dom',
    'internet': 'internet',
    'invite': 'zapraszać',
    'late': 'późno',
    'laugh': 'śmiać się',
    'leave': 'wychodzić/opuszczać',
    'library': 'biblioteka',
    'listen to music': 'słuchać muzyki',
    'lunch': 'lunch/obiad',
    'market': 'rynek/targ',
    'meet': 'spotykać',
    'money': 'pieniądze',
    'morning': 'rano',
    'museum': 'muzeum',
    'neighbour': 'sąsiad',
    'newspaper': 'gazeta',
    'night': 'noc',
    'open': 'otwarty',
    'party': 'przyjęcie',
    'pay': 'płacić',
    'phone': 'telefon',
    'play': 'bawić się/grać',
    'post office': 'poczta',
    'price': 'cena',
    'radio': 'radio',
    'read': 'czytać',
    'receipt': 'paragon',
    'relax': 'odpoczywać',
    'restaurant': 'restauracja',
    'return': 'wracać/zwracać',
    'sale': 'wyprzedaż',
    'shop': 'sklep',
    'shopping': 'zakupy',
    'shopping centre': 'centrum handlowe',
    'shower': 'prysznic',
    'sleep': 'spać',
    'spend time': 'spędzać czas',
    'supermarket': 'supermarket',
    'swimming pool': 'basen',
    'talk': 'rozmawiać',
    'tv': 'telewizja',
    'visit': 'odwiedzać',
    'wait': 'czekać',
    'wake up': 'budzić się',
    'walk': 'spacerować',
    'wash': 'myć',
    'watch': 'oglądać/zegarek',
    'weekend': 'weekend',
    'work': 'pracować'
  }),
  ...createCards('Żywienie', {
    'apple': 'jabłko',
    'bacon': 'bekon',
    'bake': 'piec',
    'banana': 'banan',
    'bean': 'fasola',
    'beef': 'wołowina',
    'beer': 'piwo',
    'bill': 'rachunek',
    'biscuit': 'ciastko',
    'bitter': 'gorzki',
    'boil': 'gotować (w wodzie)',
    'bottle': 'butelka',
    'bowl': 'miska',
    'bread': 'chleb',
    'breakfast': 'śniadanie',
    'butter': 'masło',
    'cabbage': 'kapusta',
    'cafe': 'kawiarnia',
    'cake': 'ciasto',
    'can': 'puszka',
    'candy': 'słodycze',
    'carrot': 'marchewka',
    'cheese': 'ser',
    'chef': 'szef kuchni',
    'chicken': 'kurczak',
    'chips': 'frytki',
    'chocolate': 'czekolada',
    'coffee': 'kawa',
    'cook': 'gotować/kucharz',
    'cream': 'śmietana',
    'cucumber': 'ogórek',
    'cup': 'filiżanka',
    'cut': 'kroić',
    'delicious': 'pyszny',
    'dessert': 'deser',
    'diet': 'dieta',
    'dinner': 'obiad/kolacja',
    'dish': 'potrawa/naczynie',
    'drink': 'pić',
    'eat': 'jeść',
    'egg': 'jajko',
    'fish': 'ryba',
    'flour': 'mąka',
    'food': 'jedzenie',
    'fork': 'widelec',
    'fresh': 'świeży',
    'fruit': 'owoce',
    'fry': 'smażyć',
    'garlic': 'czosnek',
    'glass': 'szklanka',
    'grape': 'winogrono',
    'grill': 'grillować',
    'ham': 'szynka',
    'healthy': 'zdrowy',
    'honey': 'miód',
    'hot': 'gorący/ostry',
    'hungry': 'głodny',
    'ice cream': 'lody',
    'ingredients': 'składniki',
    'jam': 'dżem',
    'juice': 'sok',
    'kitchen': 'kuchnia',
    'knife': 'nóż',
    'lemon': 'cytryna',
    'lettuce': 'sałata',
    'lunch': 'lunch',
    'main course': 'danie główne',
    'meal': 'posiłek',
    'meat': 'mięso',
    'menu': 'menu',
    'milk': 'mleko',
    'mineral water': 'woda mineralna',
    'mushroom': 'grzyb',
    'oil': 'olej',
    'onion': 'cebula',
    'orange': 'pomarańcza',
    'order': 'zamawiać',
    'pasta': 'makaron',
    'pepper': 'pieprz/papryka',
    'piece': 'kawałek',
    'pizza': 'pizza',
    'plate': 'talerz',
    'pork': 'wieprzowina',
    'potato': 'ziemniak',
    'recipe': 'przepis',
    'restaurant': 'restauracja',
    'rice': 'ryż',
    'salad': 'sałatka',
    'salt': 'sól',
    'sandwich': 'kanapka',
    'sausage': 'kiełbasa',
    'slice': 'plasterek',
    'snack': 'przekąska',
    'soup': 'zupa',
    'sour': 'kwaśny',
    'spoon': 'łyżka',
    'starter': 'przystawka',
    'steak': 'stek',
    'strawberry': 'truskawka',
    'sugar': 'cukier',
    'supper': 'kolacja',
    'sweet': 'słodki/cukierek',
    'tasty': 'smaczny',
    'tea': 'herbata',
    'thirsty': 'spragniony',
    'toast': 'tost',
    'tomato': 'pomidor',
    'vegetable': 'warzywo',
    'vegetarian': 'wegetariański',
    'waiter': 'kelner',
    'water': 'woda',
    'wine': 'wino',
    'yoghurt': 'jogurt'
  }),
  ...createCards('Podróże', {
    'abroad': 'za granicą',
    'accommodation': 'zakwaterowanie',
    'airplane': 'samolot',
    'airport': 'lotnisko',
    'arrival': 'przylot',
    'arrive': 'przybyć',
    'backpack': 'plecak',
    'bag': 'torba',
    'baggage': 'bagaż',
    'beach': 'plaża',
    'bicycle': 'rower',
    'bike': 'rower/motor',
    'boat': 'łódź',
    'book': 'rezerwować',
    'border': 'granica',
    'bus': 'autobus',
    'bus station': 'dworzec autobusowy',
    'bus stop': 'przystanek autobusowy',
    'camp': 'obóz',
    'camping': 'kemping',
    'car': 'samochód',
    'castle': 'zamek',
    'coach': 'autokar',
    'country': 'kraj',
    'delayed': 'opóźniony',
    'departure': 'odlot',
    'destination': 'cel podróży',
    'drive': 'jechać/prowadzić',
    'driver': 'kierowca',
    'excursion': 'wycieczka',
    'far': 'daleko',
    'ferry': 'prom',
    'flight': 'lot',
    'fly': 'lecieć',
    'foreign': 'zagraniczny',
    'guide': 'przewodnik',
    'guidebook': 'przewodnik (książka)',
    'holiday': 'wakacje',
    'hotel': 'hotel',
    'information': 'informacja',
    'island': 'wyspa',
    'journey': 'podróż',
    'lake': 'jezioro',
    'leave': 'wyjeżdżać',
    'luggage': 'bagaż',
    'map': 'mapa',
    'miss': 'spóźnić się na (autobus)',
    'monument': 'zabytek/pomnik',
    'motorway': 'autostrada',
    'mountain': 'góra',
    'museum': 'muzeum',
    'north': 'północ',
    'ocean': 'ocean',
    'pack': 'pakować',
    'passenger': 'pasażer',
    'passport': 'paszport',
    'photo': 'zdjęcie',
    'plane': 'samolot',
    'platform': 'peron',
    'postcard': 'pocztówka',
    'railway station': 'dworzec kolejowy',
    'reception': 'recepcja',
    'reservation': 'rezerwacja',
    'return ticket': 'bilet powrotny',
    'ride': 'jechać (rowerem/konno)',
    'river': 'rzeka',
    'road': 'droga',
    'sea': 'morze',
    'ship': 'statek',
    'sightseeing': 'zwiedzanie',
    'single ticket': 'bilet w jedną stronę',
    'souvenir': 'pamiątka',
    'south': 'południe',
    'station': 'stacja',
    'stay': 'zostać/pobyt',
    'suitcase': 'walizka',
    'sunbathe': 'opalać się',
    'taxi': 'taksówka',
    'tent': 'namiot',
    'ticket': 'bilet',
    'ticket office': 'kasa biletowa',
    'timetable': 'rozkład jazdy',
    'tour': 'wycieczka objazdowa',
    'tourist': 'turysta',
    'traffic': 'ruch uliczny',
    'train': 'pociąg',
    'tram': 'tramwaj',
    'transport': 'transport',
    'travel': 'podróżować',
    'trip': 'wycieczka',
    'underground': 'metro',
    'view': 'widok',
    'visit': 'odwiedzać',
    'waiting room': 'poczekalnia',
    'way': 'droga/sposób',
    'west': 'zachód'
  }),
  ...createCards('Zdrowie', {
    'accident': 'wypadek',
    'ache': 'ból',
    'ambulance': 'karetka',
    'ankle': 'kostka',
    'appointment': 'wizyta',
    'arm': 'ręka/ramię',
    'back': 'plecy',
    'bandage': 'bandaż',
    'blood': 'krew',
    'body': 'ciało',
    'bone': 'kość',
    'brain': 'mózg',
    'break': 'złamać',
    'breathe': 'oddychać',
    'burn': 'oparzenie/oparzyć',
    'cancer': 'rak',
    'check-up': 'badanie kontrolne',
    'chemist': 'aptekarz',
    'cold': 'przeziębienie',
    'cough': 'kaszel',
    'cure': 'wyleczyć',
    'cut': 'skaleczenie/ciąć',
    'dentist': 'dentysta',
    'die': 'umrzeć',
    'diet': 'dieta',
    'disease': 'choroba (poważna)',
    'doctor': 'lekarz',
    'ear': 'ucho',
    'earache': 'ból ucha',
    'emergency': 'nagły wypadek',
    'eye': 'oko',
    'face': 'twarz',
    'feel': 'czuć się',
    'fever': 'gorączka',
    'finger': 'palec u ręki',
    'fit': 'wysportowany',
    'flu': 'grypa',
    'foot': 'stopa',
    'get better': 'poczuc się lepiej',
    'glasses': 'okulary',
    'gym': 'siłownia',
    'hair': 'włosy',
    'hand': 'dłoń',
    'head': 'głowa',
    'headache': 'ból głowy',
    'health': 'zdrowie',
    'healthy': 'zdrowy',
    'heart': 'serce',
    'hospital': 'szpital',
    'hurt': 'boleć/zranić',
    'ill': 'chory',
    'illness': 'choroba',
    'knee': 'kolano',
    'leg': 'noga',
    'life': 'życie',
    'medicine': 'lekarstwo',
    'mouth': 'usta',
    'neck': 'szyja',
    'nose': 'nos',
    'nurse': 'pielęgniarka',
    'operation': 'operacja',
    'pain': 'ból',
    'painkiller': 'środek przeciwbólowy',
    'patient': 'pacjent',
    'pharmacy': 'apteka',
    'pill': 'tabletka',
    'prescription': 'recepta',
    'recover': 'wyzdrowieć',
    'runny nose': 'katar',
    'sick': 'chory',
    'skin': 'skóra',
    'sleep': 'sen',
    'smoke': 'palić',
    'soap': 'mydło',
    'sore throat': 'ból gardła',
    'stomach': 'żołądek',
    'stomach ache': 'ból brzucha',
    'stress': 'stres',
    'surgeon': 'chirurg',
    'symptom': 'objaw',
    'temperature': 'temperatura',
    'tired': 'zmęczony',
    'toe': 'palec u nogi',
    'tooth': 'ząb',
    'toothache': 'ból zęba',
    'toothbrush': 'szczoteczka do zębów',
    'treatment': 'leczenie',
    'unhealthy': 'niezdrowy',
    'virus': 'wirus',
    'vitamin': 'witamina',
    'weight': 'waga'
  }),
  ...createCards('Kultura', {
    'act': 'grać (w filmie)',
    'action film': 'film akcji',
    'actor': 'aktor',
    'actress': 'aktorka',
    'admission': 'wstęp',
    'advert': 'reklama',
    'art': 'sztuka',
    'artist': 'artysta',
    'audience': 'widownia',
    'author': 'autor',
    'band': 'zespół muzyczny',
    'book': 'książka',
    'camera': 'kamera/aparat',
    'cartoon': 'kreskówka',
    'celebrity': 'celebryta',
    'channel': 'kanał',
    'character': 'postać',
    'cinema': 'kino',
    'circus': 'cyrk',
    'comedy': 'komedia',
    'comic': 'komiks',
    'concert': 'koncert',
    'costume': 'kostium',
    'dance': 'taniec',
    'dancer': 'tancerz',
    'director': 'reżyser',
    'documentary': 'film dokumentalny',
    'draw': 'rysować',
    'drawing': 'rysunek',
    'drum': 'bęben',
    'entertainment': 'rozrywka',
    'exhibition': 'wystawa',
    'festival': 'festiwal',
    'fiction': 'fikcja',
    'film': 'film',
    'film star': 'gwiazda filmowa',
    'gallery': 'galeria',
    'guitar': 'gitara',
    'hero': 'bohater',
    'hit': 'przebój',
    'horror': 'horror',
    'instrument': 'instrument',
    'interview': 'wywiad',
    'jazz': 'jazz',
    'library': 'biblioteka',
    'literature': 'literatura',
    'magazine': 'czasopismo',
    'movie': 'film',
    'museum': 'muzeum',
    'music': 'muzyka',
    'musician': 'muzyk',
    'news': 'wiadomości',
    'novel': 'powieść',
    'opera': 'opera',
    'orchestra': 'orkiestra',
    'paint': 'malować',
    'painter': 'malarz',
    'painting': 'obraz',
    'performance': 'występ/przedstawienie',
    'photo': 'zdjęcie',
    'photographer': 'fotograf',
    'piano': 'pianino',
    'play': 'sztuka teatralna/grać',
    'poem': 'wiersz',
    'poet': 'poeta',
    'pop music': 'muzyka pop',
    'programme': 'program',
    'radio': 'radio',
    'read': 'czytać',
    'review': 'recenzja',
    'rock': 'rock',
    'row': 'rząd',
    'scene': 'scena (w filmie)',
    'screen': 'ekran',
    'sculpture': 'rzeźba',
    'seat': 'siedzenie',
    'show': 'przedstawienie/pokaz',
    'singer': 'piosenkarz',
    'song': 'piosenka',
    'stage': 'scena',
    'star': 'gwiazda',
    'story': 'historia',
    'studio': 'studio',
    'theatre': 'teatr',
    'ticket': 'bilet',
    'title': 'tytuł',
    'tv': 'telewizja',
    'video': 'wideo',
    'violin': 'skrzypce',
    'writer': 'pisarz'
  }),
  ...createCards('Przyroda', {
    'air': 'powietrze',
    'animal': 'zwierzę',
    'autumn': 'jesień',
    'beach': 'plaża',
    'bear': 'niedźwiedź',
    'bee': 'pszczoła',
    'bird': 'ptak',
    'cat': 'kot',
    'climate': 'klimat',
    'cloud': 'chmura',
    'cold': 'zimno',
    'cow': 'krowa',
    'desert': 'pustynia',
    'dog': 'pies',
    'dolphin': 'delfin',
    'dry': 'suchy',
    'duck': 'kaczka',
    'earth': 'ziemia',
    'elephant': 'słoń',
    'environment': 'środowisko',
    'field': 'pole',
    'fish': 'ryba',
    'flower': 'kwiat',
    'fog': 'mgła',
    'forest': 'las',
    'fox': 'lis',
    'frog': 'żaba',
    'giraffe': 'żyrafa',
    'grass': 'trawa',
    'green': 'zielony',
    'hill': 'wzgórze',
    'horse': 'koń',
    'hot': 'gorąco',
    'ice': 'lód',
    'insect': 'owad',
    'island': 'wyspa',
    'jungle': 'dżungla',
    'lake': 'jezioro',
    'leaf': 'liść',
    'lion': 'lew',
    'monkey': 'małpa',
    'moon': 'księżyc',
    'mosquito': 'komar',
    'mountain': 'góra',
    'mouse': 'mysz',
    'nature': 'przyroda',
    'ocean': 'ocean',
    'parrot': 'papuga',
    'pet': 'zwierzę domowe',
    'pig': 'świnia',
    'planet': 'planeta',
    'plant': 'roślina',
    'pollution': 'zanieczyszczenie',
    'rabbit': 'królik',
    'rain': 'deszcz',
    'rainforest': 'las deszczowy',
    'recycle': 'przetwarzać',
    'river': 'rzeka',
    'rock': 'skała',
    'sand': 'piasek',
    'sea': 'morze',
    'season': 'pora roku',
    'shark': 'rekin',
    'sheep': 'owca',
    'sky': 'niebo',
    'snake': 'wąż',
    'snow': 'śnieg',
    'spider': 'pająk',
    'spring': 'wiosna',
    'star': 'gwiazda',
    'stone': 'kamień',
    'storm': 'burza',
    'summer': 'lato',
    'sun': 'słońce',
    'sunny': 'słonecznie',
    'tiger': 'tygrys',
    'tree': 'drzewo',
    'view': 'widok',
    'warm': 'ciepło',
    'water': 'woda',
    'weather': 'pogoda',
    'wet': 'mokry',
    'whale': 'wieloryb',
    'wild': 'dziki',
    'wind': 'wiatr',
    'winter': 'zima',
    'wolf': 'wilk',
    'wood': 'drewno/las',
    'world': 'świat',
    'zoo': 'zoo'
  }),
  ...createCards('Nauka i technika', {
    'app': 'aplikacja',
    'astronaut': 'astronauta',
    'biology': 'biologia',
    'button': 'guzik/przycisk',
    'calculator': 'kalkulator',
    'camera': 'aparat',
    'charge': 'ładować',
    'chemistry': 'chemia',
    'click': 'klikać',
    'computer': 'komputer',
    'connect': 'łączyć',
    'crash': 'zepsuć się/awaria',
    'device': 'urządzenie',
    'digital': 'cyfrowy',
    'discover': 'odkryć',
    'discovery': 'odkrycie',
    'download': 'pobierać',
    'electric': 'elektryczny',
    'electricity': 'elektryczność',
    'email': 'email',
    'engine': 'silnik',
    'experiment': 'eksperyment',
    'file': 'plik',
    'folder': 'folder',
    'game': 'gra',
    'gas': 'gaz',
    'geography': 'geografia',
    'hardware': 'sprzęt komputerowy',
    'history': 'historia',
    'install': 'instalować',
    'internet': 'internet',
    'invent': 'wynaleźć',
    'invention': 'wynalazek',
    'keyboard': 'klawiatura',
    'lab': 'laboratorium',
    'laptop': 'laptop',
    'link': 'link/łącze',
    'machine': 'maszyna',
    'maths': 'matematyka',
    'message': 'wiadomość',
    'mobile phone': 'telefon komórkowy',
    'monitor': 'monitor',
    'mouse': 'myszka',
    'network': 'sieć',
    'online': 'w sieci',
    'password': 'hasło',
    'pc': 'komputer osobisty',
    'phone': 'telefon',
    'physics': 'fizyka',
    'planet': 'planeta',
    'power': 'zasilanie/moc',
    'print': 'drukować',
    'printer': 'drukarka',
    'program': 'program',
    'radio': 'radio',
    'research': 'badania',
    'robot': 'robot',
    'save': 'zapisywać',
    'screen': 'ekran',
    'science': 'nauka',
    'scientist': 'naukowiec',
    'search': 'szukać',
    'send': 'wysyłać',
    'smartphone': 'smartfon',
    'software': 'oprogramowanie',
    'space': 'kosmos',
    'spaceship': 'statek kosmiczny',
    'speaker': 'głośnik',
    'tablet': 'tablet',
    'tech': 'technologia',
    'technology': 'technologia',
    'text': 'sms/tekst',
    'turn off': 'wyłączyć',
    'turn on': 'włączyć',
    'upload': 'przesyłać (do sieci)',
    'user': 'użytkownik',
    'video': 'wideo',
    'virus': 'wirus',
    'web': 'sieć',
    'website': 'strona internetowa',
    'wifi': 'wifi',
    'wireless': 'bezprzewodowy',
    'work': 'działać'
  })
];